- .github/workflows/build.yml
- .gitignore
- .idea/.gitignore
- .idea/ft_irc.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- CMakeLists.txt
- include/core/Server.hpp
- src/core/EventHandler.cpp
- CMake
- github build action
- `cmake` 환경 업데이트 (CMakeList.txt, build, .gitignore)
- `github` make build action 수정
> [Feature] cmake GitHub config

- include/controller/Executor.hpp
- include/core/Type.hpp
- include/entity/Channel.hpp
- src/controller/Executor.cpp
- src/entity/Channel.cpp
- mode
- mode in Executor
- setMode, is_invite_mode, is_topic_mode, is_ban_mode in Channel
- response 생성 필요
> :sparkles: feat: Add mode method of Executor

- include/controller/ChannelController.hpp
- include/controller/ClientController.hpp
- include/controller/Executor.hpp
- include/entity/Channel.hpp
- src/controller/ChannelController.cpp
- src/controller/ClientController.cpp
- src/controller/Executor.cpp
- src/entity/Channel.cpp
- topic in executor
- updateTopic in ChannelController
- add topic, updateTopic
- add isOnChannel, isReugular
- rename update to updateDetail
- topic method 인자로 fd 보다 Client * 가 들어왔으면 좋겠음
> [Feature] Add topic method of Executor

- include/controller/ChannelController.hpp
- include/controller/ClientController.hpp
- include/controller/Executor.hpp
- include/entity/Client.hpp
- src/controller/ChannelController.cpp
- src/controller/ClientController.cpp
- src/controller/Executor.cpp
- src/entity/Client.cpp
- invite in Executor
- Add _i_channel_list, insertInviteChannel  in Client
- Add hasPermission in ChannelController
- Add insertInviteChannel in ClientController
- Client member variable 추가됨
> [Feature] Add invite method of Executor

- .vscode/settings.json
- include/controller/Executor.hpp
- src/controller/ClientController.cpp
- src/controller/Executor.cpp
- kick in Executor
- rebase 하면서 invite 브랜치가 앞으로 나옴..
> [Feature] Add kick method of Executor 

- Makefile
- include/controller/ClientController.hpp
- include/controller/Executor.hpp
- include/core/Parser.hpp
- include/core/Socket.hpp
- include/core/Type.hpp
- include/core/Udata.hpp
- include/entity/Client.hpp
- src/controller/ClientController.cpp
- src/controller/Executor.cpp
- src/controller/StringController.cpp
- src/core/Server.cpp
- src/core/Socket.cpp
- src/core/Udata.cpp
- src/core/utility.cpp
- src/entity/Client.cpp
- server.handleConnect 에서 new Client 삭제
- 대신 controller 단에서 반환하는 Client * 사용 (`Client* create(int fd)`)
- handleAccept -> handleConnect -> (authenticate) -> handleRead
- ConnectSocket 에서 처리
- socket 객체 close 위치 변경
- socket::~socket() -> socet::delete()
- socket 객체 setFd 추가
- new Client 의 필요성 제거
- ConnectSocket 에 authenticate 관련 멤버 변수, 함수 정의
- bool auth[3] : 각각 USER, PASS, NICK 가 모두 authenticate 되면 true
- isAthenticate() 에선 auth가 모두 true 인지 확인 (READ event register 가능)
- Executor.connect 추가
-  handleConnect 에서는 Executor.connect 만 처리됨
- USER, PASS, NICK 사용
- 제안. handleAccept 에서 registerConnect 와 함께 registerTimeout
- 제안: 예외적으로 parser 에서 처리
> [Feature] Add Executor.connect, Sever.handleConnect

- .vscode/settings.json
- CMakeLists.txt
- Makefile
- include/controller/ChannelController.hpp
- include/controller/ClientController.hpp
- include/controller/Executer.hpp
- include/controller/Executor.hpp
- include/core/Parser.hpp
- include/core/Server.hpp
- include/core/Socket.hpp
- include/core/Type.hpp
- include/core/Udata.hpp
- include/entity/Channel.hpp
- include/entity/Client.hpp
- src/controller/ChannelController.cpp
- src/controller/ClientController.cpp
- src/controller/Executer.cpp
- src/controller/Executor.cpp
- src/core/Server.cpp
- src/core/Socket.cpp
- src/core/Udata.cpp
- src/core/utility.cpp
- src/entity/Channel.cpp
- src/entity/Client.cpp
- executor 함수 구현
- handleConnect
- parsing framing
- response 미구현
> [Feature] executor

- CMakeLists.txt
- Makefile
- include/core/Parser.hpp
- include/core/Type.hpp
- include/core/Udata.hpp
- src/core/EventHandler.cpp
- src/core/Parser.cpp
- src/core/Server.cpp
- src/core/Udata.cpp
- src/core/utility.cpp
- test/parsing_test.cpp
- IRC server command 파싱
- `irc command` parsing
```cpp
void parseQuit(e_cmd &cmd, params *&params);
void parsePass(e_cmd &cmd, params *&params);
void parseUser(e_cmd &cmd, params *&params);
void parseNick(e_cmd &cmd, params *&params);
void parseJoin(e_cmd &cmd, params *&params);
void parsePart(e_cmd &cmd, params *&params);
void parseMode(e_cmd &cmd, params *&params) {}
void parseInvite(e_cmd &cmd, params *&params);
void parseKick(e_cmd &cmd, params *&params);
void parseTopic(e_cmd &cmd, params *&params);
void parsePrivmsg(e_cmd &cmd, params *&params);
void parseNotice(e_cmd &cmd, params *&params);
void parsePing(e_cmd &cmd, params *&params);
void parse(const std::string &command_line, e_cmd &cmd, params *&params);
```
- `Parser` 내 util 함수
```cpp
int getToken(int flag);
bool isEOF();
```
- …
> [Feature] Command parsing

- include/core/Parser.hpp
- include/core/Udata.hpp
- src/core/Parser.cpp
- `MODE` 명령어 파싱
- `validate` 함수 추가
- `MODE` 명령어 파싱
```
o - give/take channel operator privileges;
i - invite-only channel flag;
t - topic settable by channel operator only flag;
```
- `validate` 함수 추가
```
static std::string &validChannelName(std::string &channel);
static std::vector<std::string> &validChannelName(std::vector<std::string> &channels);
static std::string &validNickName(std::string &nickname);
```
> [Feature] Mode parsing & Update validate function

- src/core/Parser.cpp
- `isalpha` 로 인한 `validNick` 에러 수정
- `isalpha` 로 인한 `validNick` 에러 수정
> [BugFix] validNick error

- CMakeLists.txt
- include/core/Udata.hpp
- include/handler/ErrorHandler.hpp
- src/core/Server.cpp
- src/handler/EventHandler.cpp
- `ErrorHandler` 파일 생성
- `ErrorHandler` 파일 생성
- Udata command update
> [Feature] Update errorhandler

- .vscode/settings.json
- include/controller/ChannelController.hpp
- include/controller/Executor.hpp
- include/core/Server.hpp
- include/core/Socket.hpp
- src/controller/ChannelController.cpp
- src/controller/Executor.cpp
- src/core/Server.cpp
- src/core/Socket.cpp
- test/parsing_test.cpp
- Refactor Parsing & Fix execute join error
- `std::vector<Command> commands` 로 파싱하는 로직으로 수정
- `join` 실행 수정
- `executer.createChannel` 추가
- `ChannelController.insert` 로직 업데이트
- @Kimhan-nah `JOIN #A` 하고 `PRIVMSG #A msg` 했을 때 에러 남. 확인요망
> [Feature] Refactor Parsing & Fix execute join error

- include/controller/Executor.hpp
- include/core/Server.hpp
- include/core/Socket.hpp
- include/core/Type.hpp
- include/core/Udata.hpp
- include/core/utility.hpp
- include/handler/EventHandler.hpp
- src/controller/Executor.cpp
- src/core/Server.cpp
- src/core/Socket.cpp
- src/core/utility.cpp
- src/handler/EventHandler.cpp
타이머로 타임아웃, handleClose 리팩터링
-  response 함수 -> handleExecute, handleWrite에서 사용
-  handleTimer -> EVFILT_TIMER 기능 구현
-  안쓰는 함수 isReadbale, getTicks 삭제
-  handleTimeout 은 사실 timeout 이라는 메시지를 send 하기 위해 존재합니다..
- _tmp_garbage 는 복구 가능한, 예비 쓰레기입니다!
> [Feature] write event handle

- include/controller/ChannelController.hpp
- include/controller/ClientController.hpp
- include/controller/Executor.hpp
- include/core/Socket.hpp
- include/entity/Channel.hpp
- include/entity/Client.hpp
- include/handler/ResponseHandler.hpp
- src/controller/ChannelController.cpp
- src/controller/ClientController.cpp
- src/controller/Executor.cpp
- src/core/Server.cpp
- src/core/Socket.cpp
- src/entity/Channel.cpp
- src/entity/Client.cpp
- Executor::accept
- connect_socket.createSocket,  createClient
- findInSet 추가
- find한 내용을 return 하는 것이 아닌, std::set type의 매개변수에 find한 내용을 담아주는 함수
- broadcast Executor에 뺌
- getter 리턴값으로 const & 사용
- [naming] findInSet
TODO
> [Refactor] executor

- include/controller/Executor.hpp
- include/core/Server.hpp
- include/core/Type.hpp
- include/handler/EventHandler.hpp
- src/controller/Executor.cpp
- src/core/Server.cpp
- src/handler/EventHandler.cpp
- `Executor` 에 `_fd_list` 추가
- `Server` 처리 로직 추가
- `Executor` 에 `_fd_list` 추가
- `Server` 처리 로직 추가
> [Refactor]  Refactor executer & register events

- include/controller/ChannelController.hpp
- include/entity/Channel.hpp
- src/controller/ChannelController.cpp
- src/entity/Channel.cpp
> [Refactor] createChannel

- .github/ISSUE_TEMPLATE/-refactor-.md
> [Feature] Create refactor issue template

- include/handler/ErrorHandler.hpp
- src/controller/Executor.cpp
- src/handler/ErrorHandler.cpp
- `PASS` 명령어 에러 핸들링
- `err_code` 464 추가
- password 다를시 에러 핸들링 추가
> [BugFix] Update wrong pass err_code and handling msg

- src/core/Server.cpp
- src/handler/ErrorHandler.cpp
- Fix user register error
- `Server::parse` 로 인한 errorhandling 에러 수정
- `pass` getMessage 추가
> [BugFix] Fix user register error

- include/controller/ChannelController.hpp
- include/controller/ClientController.hpp
- include/handler/ResponseHandler.hpp
- src/controller/ChannelController.cpp
- src/controller/ClientController.cpp
- src/controller/Executor.cpp
- src/core/Server.cpp
- src/handler/ResponseHandler.cpp
- join response
- join response 수정
- 채널의 모든 operators, regulars 리스트 response에 추가
- nick 수정 (본인의 nickname으로 수정 시도하면 response 생성 안 함)
- refactoring 필요..
> [BugFix] join response

- src/controller/Executor.cpp
- src/core/Parser.cpp
- `kick` 명령어 에러 수정
- `kick` 명령어 에러 수정
> [BugFix] kick (kicker) response error

- include/core/Parser.hpp
- src/core/Parser.cpp
- `MODE` 명령어 중 처리 안한거 다 무시하게 구현
- `MODE` 명령어 중 처리 안한거 다 무시하게 구현
> [BugFix] UnHandledModeException in Parser.cpp

- .vscode/settings.json
- src/controller/ChannelController.cpp
- src/controller/Executor.cpp
- src/core/Parser.cpp
- src/entity/Channel.cpp
- src/handler/ResponseHandler.cpp
- MODE error 수정
- `parseMode`에서 `-o`에서 set nickname 추가
- `Channel::setMode`에서 flag on/off 수정
- Executor에서 `isOnChannel`, `isOperator`, `isRegular` 잘못된 사용 수정
- createJoinReponse 355, 366 `RPL_**`로 수정
- topic, invite에서 사용한 isOnChannel, isOperator, isRegular은 추후 테스트하면서 확인 필요
- join에서 invite mode인지 확인하는 로직 추가 해야함
> [BugFix] MODE response 

- src/controller/ChannelController.cpp
- src/controller/Executor.cpp
- topic 동작 수정
- channel 생성될 때 topic mode on
- 이전 topic과 동일한 topic으로 변경 시도할 경우, response 생성 안 하고 무시
> [BugFix] topic 동작 수정

- include/controller/BotController.hpp
- include/core/Command.hpp
- include/core/Parser.hpp
- src/controller/BotController.cpp
- src/controller/Executor.cpp
- src/core/Parser.cpp
- src/core/Server.cpp
Parser & bot command
- bot command 추가
- nkim
- hannkim
- chaejkim
- eyersee
- parser leak error 방지
나중에 delete p; throw Exception 에 대해 더 좋은 코드 고민해보면 좋을 듯
> [Refactor] Parser & bot command
